/**
 * Dados reais dos 158 vídeos coletados e categorizados
 * Gerado automaticamente em: 2025-11-29 14:19:15
 * Edição: 2025-11-29
 * Fonte: ui/public/editions/2025-11-29.json
 */

import { Edition, Category, Video } from "./types";
import { CATEGORY_META } from "./types";

// Vídeos por categoria

const OUTROS_VIDEOS: Video[] = [
  {
    video_id: "qLqttdO33UM",
    title: "Vision: Zero Bugs — Johann Schleier-Smith, Temporal",
    channel: "AI Engineer",
    duration: "36.05",
    views: "705",
    viewCount: 705,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=qLqttdO33UM",
    publishedAt: "2025-11-24T20:16:38Z",
    likeCount: 12,
    commentCount: 3,
  },
  {
    video_id: "VCuyfJL0RQU",
    title: "What is a SuperPod?",
    channel: "Code with Ania Kubów",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=VCuyfJL0RQU",
    publishedAt: "2025-11-21T10:15:05Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "lAQmHQr9AdI",
    title: "Genspark AI Sheets 2.0｜あなたのデータ作業を、自動操縦に",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=lAQmHQr9AdI",
    publishedAt: "2025-11-21T06:59:17Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "mrtFfpyIznE",
    title: "All-in-one AI workspace: Data analysis to executive briefing in minutes 📊",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=mrtFfpyIznE",
    publishedAt: "2025-11-21T06:59:36Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "LhbbWIrCS-I",
    title: "젠스파크: 반복업무를 자동화하세요",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=LhbbWIrCS-I",
    publishedAt: "2025-11-21T06:59:43Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "4y9_XM86BDc",
    title: "Genspark Teams ｜一緒に構築し、より速く提供",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=4y9_XM86BDc",
    publishedAt: "2025-11-21T06:59:20Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "u3nOWQDtQX0",
    title: "Genspark AI Inbox｜あなたの受信箱を、自動操縦に",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=u3nOWQDtQX0",
    publishedAt: "2025-11-21T06:59:24Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "N05p4H6MfDo",
    title: "Genspark: 雑務を自動化しよう",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=N05p4H6MfDo",
    publishedAt: "2025-11-21T06:59:45Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "3550N9VGS5o",
    title: "All-in-one AI Workspace：📊 データ分析から役員向けブリーフィングまで、数分で完了",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=3550N9VGS5o",
    publishedAt: "2025-11-21T06:59:15Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "b7CEnij2ycY",
    title: "All-in-one AI workspace:Hiring on autopilot📞",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=b7CEnij2ycY",
    publishedAt: "2025-11-21T06:59:39Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "T5GsUJw9BeA",
    title: "🚀 Genspark AI Sheets 2.0｜Your Personal Data Analyst",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=T5GsUJw9BeA",
    publishedAt: "2025-11-21T06:59:27Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "q1PjRXPuj1s",
    title: "🚀 Genspark Teams｜Build together, ship faster",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=q1PjRXPuj1s",
    publishedAt: "2025-11-21T06:59:31Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "6Cjv6OIUKmw",
    title: "All-in-one AI Workspace: 📞 자동화된 채용",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=6Cjv6OIUKmw",
    publishedAt: "2025-11-21T06:58:57Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "fO8YB530ykI",
    title: "All-in-one AI Workspace: 📊 몇 분 만에 데이터 분석에서 경영진 브리핑까지",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=fO8YB530ykI",
    publishedAt: "2025-11-21T06:59:00Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "G3z93xRbWfs",
    title: "Genspark Teams｜함께 만들고, 더 빠르게 출시하세요.",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=G3z93xRbWfs",
    publishedAt: "2025-11-21T06:59:06Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "fOSVMmnBMAw",
    title: "Genspark AI Inbox | 여러분의 수신함을 자동으로 관리하세요",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=fOSVMmnBMAw",
    publishedAt: "2025-11-21T06:59:03Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "tKhUCKyKWeA",
    title: "Genspark AI 시트 2.0｜ 당신의 개인 데이터 분석가",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=tKhUCKyKWeA",
    publishedAt: "2025-11-21T06:59:09Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "cmahdNdzsVI",
    title: "s&amp;box is now an open-source game engine, and it’s built on Valve’s Source 2 and modern .NET",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=cmahdNdzsVI",
    publishedAt: "2025-11-27T02:49:24Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "xtEkFIA-L0Q",
    title: "History: An interactive 3D globe that lets you explore the history of any location on the planet.",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=xtEkFIA-L0Q",
    publishedAt: "2025-11-26T01:03:51Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "yX4cHOu7LV8",
    title: "Twitter Account Location Flag Chrome Extension  #github",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=yX4cHOu7LV8",
    publishedAt: "2025-11-24T03:52:40Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "m7ZuxZhgncA",
    title: "GitHub Trending Today #10: moss, LLM Council, mgrep, JiT, Gausian, PeekX, NanoBanana Studio, RoMa",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=m7ZuxZhgncA",
    publishedAt: "2025-11-23T12:03:55Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "BGurOTjmdEQ",
    title: "install-nothing: a tiny Rust-based terminal app that simulates installing  #github",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=BGurOTjmdEQ",
    publishedAt: "2025-11-22T04:24:05Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "9DhLKXeEaCc",
    title: "Vex — A beautiful Excel and CSV viewer built in Go.  #github #excel #terminal",
    channel: "Github Awesome",
    duration: "0.4",
    views: "4.2K",
    viewCount: 4235,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=9DhLKXeEaCc",
    publishedAt: "2025-11-29T00:40:01Z",
    likeCount: 230,
    commentCount: 4,
  },
  {
    video_id: "Bys2Uybe6M4",
    title: "3 trending open-source projects on GitHub this week: DeepSeekMath-V2, EGGROLL in C, F1 Race Replay.",
    channel: "Github Awesome",
    duration: "1.3",
    views: "4.8K",
    viewCount: 4815,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Bys2Uybe6M4",
    publishedAt: "2025-11-28T01:22:07Z",
    likeCount: 271,
    commentCount: 1,
  },
  {
    video_id: "7Pb0A00Z_NU",
    title: "A nova função de busca Profunda no NotebookLM",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=7Pb0A00Z_NU",
    publishedAt: "2025-11-26T00:11:12Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "mlESXzpoJEs",
    title: "📢 NotebookLM: Integração com o Google Drive",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=mlESXzpoJEs",
    publishedAt: "2025-11-25T09:00:53Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "bfkurYqu5vo",
    title: "NotebookLM vs JusIA: Qual busca avançada escolher?",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=bfkurYqu5vo",
    publishedAt: "2025-11-24T22:26:36Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "-y8HflU3-go",
    title: "NotebookLM: A Ferramenta que Muda o Jogo na Busca de Jurisprudências",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=-y8HflU3-go",
    publishedAt: "2025-11-24T15:01:04Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "IW5MOdvxnxo",
    title: "Por que utilizar o NotebookLM no dia a dia?",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=IW5MOdvxnxo",
    publishedAt: "2025-11-23T09:00:54Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "_yUEAa-Pw_s",
    title: "Por que investir em IA agora?",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=_yUEAa-Pw_s",
    publishedAt: "2025-11-23T00:55:09Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "avY5LUpmXfU",
    title: "Não cometa esses erros no uso de IA!",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=avY5LUpmXfU",
    publishedAt: "2025-11-22T09:01:14Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "dLf4PlR2ILc",
    title: "NotebookLM: Nova função!",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=dLf4PlR2ILc",
    publishedAt: "2025-11-22T00:05:09Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "P1-s1e1mlF0",
    title: "IA: A Importância da Escolha de Cérebros Adequados",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=P1-s1e1mlF0",
    publishedAt: "2025-11-21T16:00:51Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "BpgZyX_aGu4",
    title: "Buscas Fundamentadas com JusIA: Quando a IA Entende o Contexto do Seu Caso",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=BpgZyX_aGu4",
    publishedAt: "2025-11-21T13:01:00Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "dLdot2u5_sw",
    title: "A Black das Blacks Magalu tá ON!",
    channel: "Canaltech",
    duration: "0.8",
    views: "1.2K",
    viewCount: 1229,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=dLdot2u5_sw",
    publishedAt: "2025-11-28T23:00:52Z",
    likeCount: 114,
    commentCount: 1,
  },
  {
    video_id: "o2Ce_3cYP3Q",
    title: "Se você vive derrubando o celular ou morre de medo de molhar, o Moto G56 5G é o seu novo parceiro.",
    channel: "Canaltech",
    duration: "0.8",
    views: "3.0K",
    viewCount: 2963,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=o2Ce_3cYP3Q",
    publishedAt: "2025-11-28T20:00:47Z",
    likeCount: 294,
    commentCount: 7,
  },
  {
    video_id: "UdL8pScKz-8",
    title: "Software engineering #softwareengineering #india",
    channel: "Data Science in your pocket",
    duration: "0.1",
    views: "1.3K",
    viewCount: 1313,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=UdL8pScKz-8",
    publishedAt: "2025-11-29T09:02:47Z",
    likeCount: 5,
    commentCount: 1,
  },
  {
    video_id: "y9ybtKvn_Jk",
    title: "Se você perder isso, não tem volta…",
    channel: "NoCode StartUp",
    duration: "0.8",
    views: "209",
    viewCount: 209,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=y9ybtKvn_Jk",
    publishedAt: "2025-11-28T19:54:24Z",
    likeCount: 4,
    commentCount: 0,
  },
  {
    video_id: "iBRwmC9eJ74",
    title: "Inundações na Indonésia e na Tailândia deixam mais de 300 mortos",
    channel: "exame",
    duration: "1.4",
    views: "1.7K",
    viewCount: 1690,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=iBRwmC9eJ74",
    publishedAt: "2025-11-28T15:45:05Z",
    likeCount: 125,
    commentCount: 6,
  },
];

const FERRAMENTAS_DEV_VIDEOS: Video[] = [
  {
    video_id: "xAfp-znTRx8",
    title: "Music from AIE Code Summit - Instrumentals",
    channel: "AI Engineer",
    duration: "65.68333333333334",
    views: "136",
    viewCount: 136,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=xAfp-znTRx8",
    publishedAt: "2025-11-27T18:32:08Z",
    likeCount: 12,
    commentCount: 2,
  },
  {
    video_id: "QRWdapxMdSY",
    title: "AI Copilots for Tech Architecture: The Highest-ROI Use Case You’re Not Building — Boris B., Catio",
    channel: "AI Engineer",
    duration: "27.483333333333334",
    views: "321",
    viewCount: 321,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=QRWdapxMdSY",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 8,
    commentCount: 2,
  },
  {
    video_id: "kWOQS3XPZ10",
    title: "Developing Taste in Coding Agents: Applied Meta Neuro-Symbolic RL — Ahmad Awais, CommandCode",
    channel: "AI Engineer",
    duration: "20.866666666666667",
    views: "351",
    viewCount: 351,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=kWOQS3XPZ10",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 11,
    commentCount: 4,
  },
  {
    video_id: "JsKTQbT58BY",
    title: "The Cure for the Vibe Coding Hangover — Corey J. Gallon, Rexmore",
    channel: "AI Engineer",
    duration: "57.03333333333333",
    views: "924",
    viewCount: 924,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=JsKTQbT58BY",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 36,
    commentCount: 7,
  },
  {
    video_id: "WqZq8L-v9pA",
    title: "What Data from 20m Pull Requests Reveal About AI Transformation — Nick Arcolano, Jellyfish",
    channel: "AI Engineer",
    duration: "17.95",
    views: "708",
    viewCount: 708,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=WqZq8L-v9pA",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 18,
    commentCount: 6,
  },
  {
    video_id: "q2nHsJVy4FE",
    title: "Compilers in the Age of LLMs — Yusuf Olokoba, Muna",
    channel: "AI Engineer",
    duration: "17.6",
    views: "2.1K",
    viewCount: 2144,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=q2nHsJVy4FE",
    publishedAt: "2025-11-24T20:16:38Z",
    likeCount: 71,
    commentCount: 6,
  },
  {
    video_id: "o3gmwzo-Mik",
    title: "AI changes *Nothing* — Dax Raad, OpenCode",
    channel: "AI Engineer",
    duration: "16.65",
    views: "15.8K",
    viewCount: 15810,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=o3gmwzo-Mik",
    publishedAt: "2025-11-23T19:44:51Z",
    likeCount: 743,
    commentCount: 68,
  },
  {
    video_id: "xmbSQz-PNMM",
    title: "AIE CODE Day 2: ft Google Deepmind, Anthropic, Cursor, Netflix, Cline, OpenAI, Meta, and METR",
    channel: "AI Engineer",
    duration: "537.1",
    views: "23.3K",
    viewCount: 23272,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=xmbSQz-PNMM",
    publishedAt: "2025-11-21T23:10:16Z",
    likeCount: 494,
    commentCount: 17,
  },
  {
    video_id: "cMSprbJ95jg",
    title: "AIE CODE 2025: AI Leadership ft Anthropic, OpenAI, McKinsey, Bloomberg, Google Deepmind, and Tenex",
    channel: "AI Engineer",
    duration: "496.0833333333333",
    views: "17.5K",
    viewCount: 17544,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=cMSprbJ95jg",
    publishedAt: "2025-11-20T22:36:06Z",
    likeCount: 350,
    commentCount: 11,
  },
  {
    video_id: "x9bIWL-nwFw",
    title: "Readdy AI: This AI Builder can BUILD WEBSITES &amp; APPS that CAN SPEAK TO CUSTOMERS!",
    channel: "AICodeKing",
    duration: "7.783333333333333",
    views: "1.4K",
    viewCount: 1390,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=x9bIWL-nwFw",
    publishedAt: "2025-11-27T09:15:10Z",
    likeCount: 53,
    commentCount: 4,
  },
  {
    video_id: "J7e2n-BMtYQ",
    title: "Bind AI IDE: This AI Coder FIXES Vibe-Coding for EVERYONE!",
    channel: "AICodeKing",
    duration: "8.7",
    views: "5.0K",
    viewCount: 4960,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=J7e2n-BMtYQ",
    publishedAt: "2025-11-26T09:15:01Z",
    likeCount: 138,
    commentCount: 37,
  },
  {
    video_id: "pbUqW-MWVgY",
    title: "Google Gemini 3 Build Mode: This FULLY FREE Gemini-3 AI Coder is ACTUALLY INSANE!",
    channel: "AICodeKing",
    duration: "12.216666666666667",
    views: "15.2K",
    viewCount: 15239,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=pbUqW-MWVgY",
    publishedAt: "2025-11-24T09:15:07Z",
    likeCount: 391,
    commentCount: 38,
  },
  {
    video_id: "0S9G9mGLB1U",
    title: "Traycer YOLO MODE: Plan, Sit &amp; LET YOUR AGENT CODE! The REAL AGENTIC CODING!",
    channel: "AICodeKing",
    duration: "11.466666666666667",
    views: "5.6K",
    viewCount: 5648,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=0S9G9mGLB1U",
    publishedAt: "2025-11-22T09:15:00Z",
    likeCount: 158,
    commentCount: 21,
  },
  {
    video_id: "RmQO99zMhmk",
    title: "gitlogue. It turns your Git history into a cinematic, animated replay right inside your terminal.",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=RmQO99zMhmk",
    publishedAt: "2025-11-25T03:51:21Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "wu3522-is9w",
    title: "GitHub Trending Today #11: SyncKit, RepoMind, Vex, runprompt, Markdown Viewer, beads_viewer, Pulse",
    channel: "Github Awesome",
    duration: "10.4",
    views: "345",
    viewCount: 345,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=wu3522-is9w",
    publishedAt: "2025-11-29T15:16:27Z",
    likeCount: 17,
    commentCount: 0,
  },
  {
    video_id: "_P46asoq7h8",
    title: "Vazamento de Dados da OpenAI: O Que Você Precisa Saber!",
    channel: "Inteligencia Artificial para advogados",
    duration: "0.6",
    views: "410",
    viewCount: 410,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=_P46asoq7h8",
    publishedAt: "2025-11-28T00:16:19Z",
    likeCount: 12,
    commentCount: 0,
  },
  {
    video_id: "2NWRyT2M8xA",
    title: "Conheça o Epson EF22, o projetor smart portátil que entrega imagem Full HD até 150”",
    channel: "Canaltech",
    duration: "0.7",
    views: "4.5K",
    viewCount: 4476,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=2NWRyT2M8xA",
    publishedAt: "2025-11-27T20:32:20Z",
    likeCount: 210,
    commentCount: 0,
  },
  {
    video_id: "w9Oo25PZVA4",
    title: "Vibe Coding #vibecoding #coding #programming #ai",
    channel: "Data Science in your pocket",
    duration: "0.1",
    views: "1.4K",
    viewCount: 1412,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=w9Oo25PZVA4",
    publishedAt: "2025-11-29T04:53:41Z",
    likeCount: 8,
    commentCount: 0,
  },
  {
    video_id: "vG4B1UrcEiA",
    title: "Kimi Slides with Nano Banana Pro for Free",
    channel: "Fahd Mirza",
    duration: "13.3",
    views: "700",
    viewCount: 700,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=vG4B1UrcEiA",
    publishedAt: "2025-11-29T06:06:01Z",
    likeCount: 42,
    commentCount: 5,
  },
  {
    video_id: "JYgN98ZpN1g",
    title: "INTELLECT-3: A 100B+ MoE Trained with Large-Scale RL on GLM 4.5 AIR",
    channel: "Fahd Mirza",
    duration: "14.1",
    views: "1.3K",
    viewCount: 1257,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=JYgN98ZpN1g",
    publishedAt: "2025-11-28T06:15:17Z",
    likeCount: 53,
    commentCount: 2,
  },
  {
    video_id: "PvdptUZ3XeU",
    title: "How to vibe code responsibly (with a little help from MCPs)",
    channel: "GitHub",
    duration: "14.4",
    views: "384",
    viewCount: 384,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=PvdptUZ3XeU",
    publishedAt: "2025-11-29T15:00:51Z",
    likeCount: 41,
    commentCount: 4,
  },
  {
    video_id: "EXEtRc8oQ7E",
    title: "Replay: Open Source Friday: Secure Code Game with Bartosz Gałek & jkcso",
    channel: "GitHub",
    duration: "0.0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=EXEtRc8oQ7E",
    publishedAt: "2025-11-28T17:57:02Z",
    likeCount: 1,
    commentCount: 0,
  },
  {
    video_id: "0qdRS3xYwIY",
    title: "What is a .gitignore file and why do you need it?",
    channel: "GitHub",
    duration: "1.0",
    views: "10.3K",
    viewCount: 10309,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=0qdRS3xYwIY",
    publishedAt: "2025-11-28T15:00:03Z",
    likeCount: 249,
    commentCount: 5,
  },
  {
    video_id: "B7nTEvhF9dk",
    title: "Our Favorite Products of 2025 (Apps, Video Games, AI)",
    channel: "Greg Isenberg",
    duration: "63.1",
    views: "3.2K",
    viewCount: 3188,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=B7nTEvhF9dk",
    publishedAt: "2025-11-28T20:30:03Z",
    likeCount: 141,
    commentCount: 45,
  },
  {
    video_id: "PlY0H8Y6Vso",
    title: "Inside a Hacker Honeypot",
    channel: "IBM Technology",
    duration: "1.3",
    views: "7.9K",
    viewCount: 7902,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=PlY0H8Y6Vso",
    publishedAt: "2025-11-28T17:00:45Z",
    likeCount: 103,
    commentCount: 0,
  },
  {
    video_id: "_v0vhUU_o3Q",
    title: "Tributação de dividendos: quem será impactado",
    channel: "InvestNews BR",
    duration: "6.3",
    views: "976",
    viewCount: 976,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=_v0vhUU_o3Q",
    publishedAt: "2025-11-28T13:25:47Z",
    likeCount: 75,
    commentCount: 13,
  },
  {
    video_id: "sIuF013udPY",
    title: "Matt and Ryan have a chat on December 02, 2025",
    channel: "Matt Williams",
    duration: "0.0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=sIuF013udPY",
    publishedAt: "2025-11-28T23:10:03Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "Q1tgc3WTb2k",
    title: "Microsoft's EVP of AI talks OpenAI, Datacenters, Future of Coding, Open v Closed and more",
    channel: "Matthew Berman",
    duration: "40.4",
    views: "4.6K",
    viewCount: 4553,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Q1tgc3WTb2k",
    publishedAt: "2025-11-28T20:24:46Z",
    likeCount: 100,
    commentCount: 49,
  },
  {
    video_id: "XySWH6O3Cso",
    title: "🔥 A Nova IA Que Constrói Apps COMPLETOS Sozinha! Skywork AI Developer Vale a Pena?",
    channel: "Onde eu Clico",
    duration: "9.5",
    views: "913",
    viewCount: 913,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=XySWH6O3Cso",
    publishedAt: "2025-11-29T14:01:02Z",
    likeCount: 152,
    commentCount: 15,
  },
  {
    video_id: "FkaGi1WowRE",
    title: "🤖MeDo da Baidu: A Ferramenta que Vai Revolucionar o No Code - GRÁTIS",
    channel: "Onde eu Clico",
    duration: "13.6",
    views: "6.7K",
    viewCount: 6653,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=FkaGi1WowRE",
    publishedAt: "2025-11-28T14:00:21Z",
    likeCount: 533,
    commentCount: 68,
  },
  {
    video_id: "xIJoGOvT94Y",
    title: "🔥Ainda é BLACK FRIDAY! Vai perder a CHANCE? Últimas ofertas, cupons e promoções",
    channel: "TecMundo",
    duration: "249.7",
    views: "8.6K",
    viewCount: 8581,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=xIJoGOvT94Y",
    publishedAt: "2025-11-28T20:25:09Z",
    likeCount: 520,
    commentCount: 1,
  },
  {
    video_id: "Ce3FvoHyXDI",
    title: "🚨🔥Black Friday AO VIVO! Promoção, cupom e desconto AQUI!",
    channel: "TecMundo",
    duration: "532.8",
    views: "19.6K",
    viewCount: 19583,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Ce3FvoHyXDI",
    publishedAt: "2025-11-28T04:25:25Z",
    likeCount: 920,
    commentCount: 2,
  },
  {
    video_id: "il0dFcWBev0",
    title: "Did you know about the range function?",
    channel: "Tech With Tim",
    duration: "1.8",
    views: "892",
    viewCount: 892,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=il0dFcWBev0",
    publishedAt: "2025-11-29T16:38:34Z",
    likeCount: 29,
    commentCount: 1,
  },
  {
    video_id: "KXjccJm-06I",
    title: "You need to follow a system...",
    channel: "Tech With Tim",
    duration: "0.9",
    views: "14.5K",
    viewCount: 14460,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=KXjccJm-06I",
    publishedAt: "2025-11-28T09:14:39Z",
    likeCount: 461,
    commentCount: 17,
  },
];

const NOVOS_MODELOS_VIDEOS: Video[] = [
  {
    video_id: "LLuKshphGOE",
    title: "Context Engineering: Connecting the Dots with Graphs — Stephen Chin, Neo4j",
    channel: "AI Engineer",
    duration: "26.833333333333332",
    views: "1.4K",
    viewCount: 1415,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=LLuKshphGOE",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 34,
    commentCount: 9,
  },
  {
    video_id: "IZhGvZ4UlPs",
    title: "Here&#39;s What They Didn&#39;t Tell You About Claude&#39;s New Model - Opus 4.5",
    channel: "AI LABS",
    duration: "9.266666666666667",
    views: "10.2K",
    viewCount: 10186,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=IZhGvZ4UlPs",
    publishedAt: "2025-11-25T15:43:57Z",
    likeCount: 274,
    commentCount: 30,
  },
  {
    video_id: "eLDq5TfIHys",
    title: "Claude Just Introduced a New Way To Fix Your UI",
    channel: "AI LABS",
    duration: "10.833333333333334",
    views: "42.9K",
    viewCount: 42947,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=eLDq5TfIHys",
    publishedAt: "2025-11-23T13:14:28Z",
    likeCount: 969,
    commentCount: 38,
  },
  {
    video_id: "opZpIN8g_6M",
    title: "Claude Just Solved Their Biggest Problem",
    channel: "AI LABS",
    duration: "9.4",
    views: "17.7K",
    viewCount: 17730,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=opZpIN8g_6M",
    publishedAt: "2025-11-21T13:45:11Z",
    likeCount: 466,
    commentCount: 59,
  },
  {
    video_id: "5nxnNRYQIoI",
    title: "5 Things I Bet You Didn't Know About Antigravity",
    channel: "AI LABS",
    duration: "3.7",
    views: "1.9K",
    viewCount: 1926,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=5nxnNRYQIoI",
    publishedAt: "2025-11-29T12:35:38Z",
    likeCount: 107,
    commentCount: 20,
  },
  {
    video_id: "XzeXELTd84s",
    title: "Gemini 3 + NotebookLM creates stunning VISUALS & CHARTS in minutes!",
    channel: "AI and Tech for Education",
    duration: "9.5",
    views: "9.5K",
    viewCount: 9525,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=XzeXELTd84s",
    publishedAt: "2025-11-28T12:30:53Z",
    likeCount: 494,
    commentCount: 28,
  },
  {
    video_id: "I60MFVKFMlc",
    title: "Claude Opus 4.5 (Fully Tested): Anthropic REALLY COOKED with this model! #1 on my Agentic Tests!",
    channel: "AICodeKing",
    duration: "11.233333333333333",
    views: "14.7K",
    viewCount: 14695,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=I60MFVKFMlc",
    publishedAt: "2025-11-25T11:36:28Z",
    likeCount: 482,
    commentCount: 70,
  },
  {
    video_id: "0Mjd8TbKzxc",
    title: "Gemini CLI 6.0: Google JUST INTEGRATED Gemini-3 into Gemini CLI &amp; IT&#39;S INSANE!",
    channel: "AICodeKing",
    duration: "9.366666666666667",
    views: "23.4K",
    viewCount: 23424,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=0Mjd8TbKzxc",
    publishedAt: "2025-11-23T09:15:00Z",
    likeCount: 564,
    commentCount: 75,
  },
  {
    video_id: "WvfECHWdbkY",
    title: "Google Stitch 4.0 (Upgraded): Google&#39;s Gemini-3 &amp; Nano Banana Pro Designer is ACTUALLY INSANE!",
    channel: "AICodeKing",
    duration: "10.316666666666666",
    views: "18.7K",
    viewCount: 18747,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=WvfECHWdbkY",
    publishedAt: "2025-11-21T11:38:26Z",
    likeCount: 583,
    commentCount: 30,
  },
  {
    video_id: "JQAyw4webmU",
    title: "4.5 Opus + Gemini 3 Pro: INSANE Coding Results at LOW COST!",
    channel: "AICodeKing",
    duration: "9.7",
    views: "7.0K",
    viewCount: 7012,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=JQAyw4webmU",
    publishedAt: "2025-11-29T09:15:04Z",
    likeCount: 340,
    commentCount: 38,
  },
  {
    video_id: "yVd3rZxuGS0",
    title: "Genspark Live 2025",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=yVd3rZxuGS0",
    publishedAt: "2025-11-21T13:04:29Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "KHzLctOWbA4",
    title: "🚀 Genspark AI Inbox｜Your inbox, on autopilot",
    channel: "Genspark",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=KHzLctOWbA4",
    publishedAt: "2025-11-21T06:59:34Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "Br4bW9PsOiQ",
    title: "LLM Council: a project that basically turns your favorite AI models into a panel of experts #github",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Br4bW9PsOiQ",
    publishedAt: "2025-11-23T04:11:29Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "707na7SqjS0",
    title: "NotebookLM vs Gemini: Qual é melhor?",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=707na7SqjS0",
    publishedAt: "2025-11-24T09:01:00Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "aQLsDU_ln_I",
    title: "🤖 O Ranking das IAs Mais Avançadas em 2024",
    channel: "Inteligencia Artificial para advogados",
    duration: "0.6",
    views: "955",
    viewCount: 955,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=aQLsDU_ln_I",
    publishedAt: "2025-11-28T09:01:02Z",
    likeCount: 11,
    commentCount: 0,
  },
  {
    video_id: "69ZkuYl7ugA",
    title: "Crie seu Hub de IAs no WhatsApp — ChatGPT + Gemini no mesmo robô!",
    channel: "Comunidade ZDG",
    duration: "9.1",
    views: "291",
    viewCount: 291,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=69ZkuYl7ugA",
    publishedAt: "2025-11-28T20:01:09Z",
    likeCount: 22,
    commentCount: 1,
  },
  {
    video_id: "llwZEywL2sI",
    title: "Z-Image-Turbo : Smallest AI Image Generator ",
    channel: "Data Science in your pocket",
    duration: "4.2",
    views: "118",
    viewCount: 118,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=llwZEywL2sI",
    publishedAt: "2025-11-28T13:48:06Z",
    likeCount: 9,
    commentCount: 0,
  },
  {
    video_id: "t0m4ye0xjTA",
    title: "DeepSeek Math-V2 : New DeepSeek Math reasoning model",
    channel: "Data Science in your pocket",
    duration: "3.9",
    views: "333",
    viewCount: 333,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=t0m4ye0xjTA",
    publishedAt: "2025-11-28T13:27:15Z",
    likeCount: 12,
    commentCount: 0,
  },
  {
    video_id: "iRZxlYtn9_0",
    title: "Step-Audio-R1: How Not to Create an Audio Model",
    channel: "Fahd Mirza",
    duration: "10.5",
    views: "843",
    viewCount: 843,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=iRZxlYtn9_0",
    publishedAt: "2025-11-29T02:00:58Z",
    likeCount: 47,
    commentCount: 4,
  },
  {
    video_id: "tNTLld3HtfI",
    title: "ResilientLLM - LLM Integration Layer For Production",
    channel: "Fahd Mirza",
    duration: "8.1",
    views: "572",
    viewCount: 572,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=tNTLld3HtfI",
    publishedAt: "2025-11-28T19:35:29Z",
    likeCount: 29,
    commentCount: 4,
  },
  {
    video_id: "lwrPjDQkVCQ",
    title: "Did These Models Just Beat Google?",
    channel: "Matt Wolfe",
    duration: "38.2",
    views: "27.7K",
    viewCount: 27686,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=lwrPjDQkVCQ",
    publishedAt: "2025-11-28T20:47:34Z",
    likeCount: 1109,
    commentCount: 106,
  },
  {
    video_id: "ub8h9dCJ4mk",
    title: "LIVE (27/11) - Z-Image (Censura Zero), Imagens Interativas no Gemini, Deepseek Math V2 e MUITO MAIS",
    channel: "Onde eu Clico",
    duration: "56.2",
    views: "898",
    viewCount: 898,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=ub8h9dCJ4mk",
    publishedAt: "2025-11-28T11:00:38Z",
    likeCount: 107,
    commentCount: 1,
  },
  {
    video_id: "TvM5i-NgrwA",
    title: "Z-Image Turbo in Action – Fast Image Generation with ComfyUI",
    channel: "Prompt Engineer",
    duration: "12.8",
    views: "130",
    viewCount: 130,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=TvM5i-NgrwA",
    publishedAt: "2025-11-29T09:43:53Z",
    likeCount: 9,
    commentCount: 0,
  },
  {
    video_id: "8Svr2A_Pt7o",
    title: "Gemini 3.0 Flash: Google's Greatest Model Ever? Most Powerful, Cheapest, & Fastest Model Ever (Leak)",
    channel: "WorldofAI",
    duration: "9.8",
    views: "9.4K",
    viewCount: 9393,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=8Svr2A_Pt7o",
    publishedAt: "2025-11-27T22:28:23Z",
    likeCount: 234,
    commentCount: 23,
  },
  {
    video_id: "NfiIXoWyOLI",
    title: "Why China’s Ports Empire Has the US Worried",
    channel: "Bloomberg Originals",
    duration: "10.8",
    views: "112.5K",
    viewCount: 112454,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=NfiIXoWyOLI",
    publishedAt: "2025-11-28T09:00:46Z",
    likeCount: 2273,
    commentCount: 429,
  },
];

const TUTORIAIS_VIDEOS: Video[] = [
  {
    video_id: "m6MF1OR_9kM",
    title: "Z.ai GLM 4.6: What We Learned From 100 Million Open Source Downloads — Yuxuan Zhang, Z.ai",
    channel: "AI Engineer",
    duration: "19.65",
    views: "4.2K",
    viewCount: 4200,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=m6MF1OR_9kM",
    publishedAt: "2025-11-22T15:00:06Z",
    likeCount: 101,
    commentCount: 3,
  },
  {
    video_id: "SdvQyKB-kDs",
    title: "NotebookLM: Como uma IA transforma pesquisa em relatórios profissionais",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=SdvQyKB-kDs",
    publishedAt: "2025-11-23T23:43:21Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "07m4AX7njMc",
    title: "🔒 IA: Aprenda a proteger seus dados!",
    channel: "Inteligencia Artificial para advogados",
    duration: "0.8",
    views: "281",
    viewCount: 281,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=07m4AX7njMc",
    publishedAt: "2025-11-28T15:01:17Z",
    likeCount: 5,
    commentCount: 0,
  },
  {
    video_id: "n112vfmsgeE",
    title: "Como automatizar TUDO de graça e SEM limites",
    channel: "Billy Automações",
    duration: "12.1",
    views: "91",
    viewCount: 91,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=n112vfmsgeE",
    publishedAt: "2025-11-27T21:00:54Z",
    likeCount: 8,
    commentCount: 0,
  },
  {
    video_id: "PnQWQxBLbf0",
    title: "Anvisa proibiu anel que promete medir glicose | Qual realmente funciona?",
    channel: "Canaltech",
    duration: "9.0",
    views: "239",
    viewCount: 239,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=PnQWQxBLbf0",
    publishedAt: "2025-11-29T17:00:43Z",
    likeCount: 39,
    commentCount: 2,
  },
  {
    video_id: "cZWzygZjuaM",
    title: "Não é mágica, é tecnologia pura! ✨ Fomos conferir de perto como a mágica acontece na fábrica da Oppo",
    channel: "Canaltech",
    duration: "1.2",
    views: "1.3K",
    viewCount: 1281,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=cZWzygZjuaM",
    publishedAt: "2025-11-29T15:01:14Z",
    likeCount: 246,
    commentCount: 3,
  },
  {
    video_id: "djWDrK2Ogh4",
    title: "IA e Nuvem na Prática: Estratégias da AWS para a Black Friday",
    channel: "Canaltech",
    duration: "41.6",
    views: "1.4K",
    viewCount: 1410,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=djWDrK2Ogh4",
    publishedAt: "2025-11-28T21:00:47Z",
    likeCount: 135,
    commentCount: 2,
  },
  {
    video_id: "dBqDsQsrnI0",
    title: "Te dou 5 segundos: qual é o iPhone 17 e qual é o 16? 🧐",
    channel: "Canaltech",
    duration: "2.3",
    views: "6.7K",
    viewCount: 6688,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=dBqDsQsrnI0",
    publishedAt: "2025-11-28T15:18:19Z",
    likeCount: 748,
    commentCount: 12,
  },
  {
    video_id: "gzXykEumCC8",
    title: "1 CTO vs 100 PROGRAMADORES | ft. FILIPE DESCHAMPS",
    channel: "Filipe Deschamps",
    duration: "455.4",
    views: "30.5K",
    viewCount: 30532,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=gzXykEumCC8",
    publishedAt: "2025-11-28T21:30:09Z",
    likeCount: 1934,
    commentCount: 14,
  },
  {
    video_id: "O9s3-VXNi94",
    title: "[ptBR]🇧🇷✨ Open Source Friday Brazil  com Priscila Gutierres & Guinevere Larsen",
    channel: "GitHub",
    duration: "53.0",
    views: "772",
    viewCount: 772,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=O9s3-VXNi94",
    publishedAt: "2025-11-29T05:04:26Z",
    likeCount: 28,
    commentCount: 0,
  },
  {
    video_id: "a7v3Zrke7jk",
    title: "Como as estatais chinesas estão investindo em portos e ferrovias do Brasil",
    channel: "InvestNews BR",
    duration: "8.5",
    views: "13.3K",
    viewCount: 13310,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=a7v3Zrke7jk",
    publishedAt: "2025-11-28T21:13:05Z",
    likeCount: 970,
    commentCount: 52,
  },
  {
    video_id: "9_xUsL9uFlo",
    title: "Roberto Campos Neto: As stablecoins como financiadoras da dívida americana",
    channel: "InvestNews BR",
    duration: "0.9",
    views: "743",
    viewCount: 743,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=9_xUsL9uFlo",
    publishedAt: "2025-11-27T21:46:04Z",
    likeCount: 34,
    commentCount: 0,
  },
  {
    video_id: "91JaJbiHKN8",
    title: "Plaud: A ferramenta de IA que transforma reuniões e ligações em resumos e tarefas",
    channel: "InvestNews BR",
    duration: "5.5",
    views: "4.5K",
    viewCount: 4527,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=91JaJbiHKN8",
    publishedAt: "2025-11-27T21:00:07Z",
    likeCount: 343,
    commentCount: 13,
  },
  {
    video_id: "LukbMZtPQyk",
    title: "Gemini 3 Humilhado? IA GRÁTIS que cria App, Site, Micro-SaaS, QUALQUER COISA! Mostro Passo a Passo",
    channel: "Manual de Inteligência Artificial",
    duration: "12.8",
    views: "956",
    viewCount: 956,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=LukbMZtPQyk",
    publishedAt: "2025-11-28T13:00:43Z",
    likeCount: 64,
    commentCount: 9,
  },
  {
    video_id: "pnpJ4xkuwE0",
    title: "Os melhores processadores para montar seu PC em 2025",
    channel: "TecMundo",
    duration: "8.9",
    views: "452",
    viewCount: 452,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=pnpJ4xkuwE0",
    publishedAt: "2025-11-29T14:01:31Z",
    likeCount: 114,
    commentCount: 6,
  },
  {
    video_id: "2J2dliDRixE",
    title: "Oreo + Wandinha: seu destindo ácido ainda tá a um clique",
    channel: "TecMundo",
    duration: "0.8",
    views: "222",
    viewCount: 222,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=2J2dliDRixE",
    publishedAt: "2025-11-29T13:00:06Z",
    likeCount: 5,
    commentCount: 0,
  },
  {
    video_id: "eBSix1QMK4E",
    title: "UM SIMPLES XIXI PODE SALVAR SUA VIDA!",
    channel: "TecMundo",
    duration: "0.7",
    views: "5.5K",
    viewCount: 5526,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=eBSix1QMK4E",
    publishedAt: "2025-11-28T18:00:55Z",
    likeCount: 452,
    commentCount: 12,
  },
  {
    video_id: "t9JlWQXWHuU",
    title: "TecFriday apresenta: Preço na Medida – Parte 3",
    channel: "TecMundo",
    duration: "1.0",
    views: "4.7K",
    viewCount: 4695,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=t9JlWQXWHuU",
    publishedAt: "2025-11-28T16:30:32Z",
    likeCount: 23,
    commentCount: 1,
  },
  {
    video_id: "qjVjiH2O4Pc",
    title: "5 lojas gringas para comprar na Black Friday",
    channel: "TecMundo",
    duration: "7.0",
    views: "19.1K",
    viewCount: 19150,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=qjVjiH2O4Pc",
    publishedAt: "2025-11-27T23:30:20Z",
    likeCount: 55,
    commentCount: 0,
  },
  {
    video_id: "J2fol8eWo64",
    title: "Data Structures  - Full Course for Beginners",
    channel: "Tech With Tim",
    duration: "191.1",
    views: "12.1K",
    viewCount: 12113,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=J2fol8eWo64",
    publishedAt: "2025-11-28T09:33:02Z",
    likeCount: 928,
    commentCount: 33,
  },
];

const AGENTES_IA_VIDEOS: Video[] = [
  {
    video_id: "qqXdLf3wy1E",
    title: "Agents are Robots Too: What Self-Driving Taught Me About Building Agents — Jesse Hu, Abundant",
    channel: "AI Engineer",
    duration: "17.616666666666667",
    views: "776",
    viewCount: 776,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=qqXdLf3wy1E",
    publishedAt: "2025-11-24T20:16:38Z",
    likeCount: 18,
    commentCount: 3,
  },
  {
    video_id: "zMXKhhwiCIc",
    title: "Backlog.md: Terminal Kanban Board for Managing Tasks with AI Agents — Alex Gavrilescu, Funstage",
    channel: "AI Engineer",
    duration: "14.316666666666666",
    views: "1.1K",
    viewCount: 1112,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=zMXKhhwiCIc",
    publishedAt: "2025-11-24T20:16:38Z",
    likeCount: 28,
    commentCount: 4,
  },
  {
    video_id: "zfvEMNmVlNY",
    title: "The Unbearable Lightness of Agent Optimization — Alberto Romero, Jointly",
    channel: "AI Engineer",
    duration: "17.966666666666665",
    views: "981",
    viewCount: 981,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=zfvEMNmVlNY",
    publishedAt: "2025-11-24T20:16:38Z",
    likeCount: 23,
    commentCount: 2,
  },
  {
    video_id: "flf_IKnFYnE",
    title: "From Stateless Nightmares to Durable Agents — Samuel Colvin, Pydantic",
    channel: "AI Engineer",
    duration: "22.216666666666665",
    views: "2.9K",
    viewCount: 2931,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=flf_IKnFYnE",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 71,
    commentCount: 5,
  },
  {
    video_id: "5eJqXtevlXg",
    title: "Hacking Subagents Into Codex CLI — Brian John, Betterup",
    channel: "AI Engineer",
    duration: "13.65",
    views: "503",
    viewCount: 503,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=5eJqXtevlXg",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 11,
    commentCount: 1,
  },
  {
    video_id: "NTBX-wxUhHs",
    title: "Context Platform Engineering to Reduce Token Anxiety — Val Bercovici, WEKA",
    channel: "AI Engineer",
    duration: "23.866666666666667",
    views: "413",
    viewCount: 413,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=NTBX-wxUhHs",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 8,
    commentCount: 3,
  },
  {
    video_id: "Q5IVm_CxN2w",
    title: "Infra that fixes itself, thanks to coding agents — Mahmoud Abdelwahab, Railway",
    channel: "AI Engineer",
    duration: "18.133333333333333",
    views: "345",
    viewCount: 345,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Q5IVm_CxN2w",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 7,
    commentCount: 2,
  },
  {
    video_id: "ckrvwCLPwVw",
    title: "RTRVR 2.0: This is THE BEST AI AGENT YET! Can do ANYTHING from ONE PROMPT!",
    channel: "AICodeKing",
    duration: "8.2",
    views: "4.9K",
    viewCount: 4873,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=ckrvwCLPwVw",
    publishedAt: "2025-11-28T09:15:06Z",
    likeCount: 179,
    commentCount: 5,
  },
  {
    video_id: "7ad_1mC-zCk",
    title: "Anthropic Just Made Code‑Execution Agents Easy (But Dangerous)",
    channel: "Arseny Shatokhin",
    duration: "16.4",
    views: "2.5K",
    viewCount: 2453,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=7ad_1mC-zCk",
    publishedAt: "2025-11-28T14:10:54Z",
    likeCount: 68,
    commentCount: 9,
  },
  {
    video_id: "-eRjenGV2OM",
    title: "Rubber Duck Thursdays - Let's build with custom agents",
    channel: "GitHub",
    duration: "108.9",
    views: "758",
    viewCount: 758,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=-eRjenGV2OM",
    publishedAt: "2025-11-28T01:07:06Z",
    likeCount: 23,
    commentCount: 0,
  },
  {
    video_id: "UjQBgwTcvng",
    title: "Rogue AI Agents: How AI Observability Builds Autonomous Trust",
    channel: "IBM Technology",
    duration: "4.8",
    views: "1.2K",
    viewCount: 1209,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=UjQBgwTcvng",
    publishedAt: "2025-11-29T12:01:01Z",
    likeCount: 100,
    commentCount: 0,
  },
  {
    video_id: "SdNRWJ-oqjY",
    title: "AI agents in 2025: Why agentic commerce isn't ready for Black Friday yet",
    channel: "IBM Technology",
    duration: "41.5",
    views: "1.9K",
    viewCount: 1899,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=SdNRWJ-oqjY",
    publishedAt: "2025-11-28T11:00:54Z",
    likeCount: 64,
    commentCount: 6,
  },
  {
    video_id: "rVnU-k9ni0Y",
    title: "Will It Extract | Episode 3 - Black Friday Sale",
    channel: "LandingAI",
    duration: "1.2",
    views: "25",
    viewCount: 25,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=rVnU-k9ni0Y",
    publishedAt: "2025-11-28T18:02:41Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "gsevjVkN9KA",
    title: "Top New Open-Source GitHub Projects This Week: AI Agents, Web Tools & Dev Kits #211",
    channel: "ManuAGI - AutoGPT Tutorials",
    duration: "14.1",
    views: "483",
    viewCount: 483,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=gsevjVkN9KA",
    publishedAt: "2025-11-29T13:45:04Z",
    likeCount: 38,
    commentCount: 0,
  },
  {
    video_id: "qQZ8gfPstFo",
    title: "Airia vs Every AI Agent Builder — Here’s Why This One Wins 😎",
    channel: "Prompt Engineer",
    duration: "19.9",
    views: "17",
    viewCount: 17,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=qQZ8gfPstFo",
    publishedAt: "2025-11-29T16:47:09Z",
    likeCount: 1,
    commentCount: 0,
  },
  {
    video_id: "fqcKRn4ZjDI",
    title: "Toolhouse: First-Ever Agent UI - Fastest & Easiest Way to Create AI Agents! NEW MCP + Toolkit!",
    channel: "WorldofAI",
    duration: "12.2",
    views: "4.7K",
    viewCount: 4657,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=fqcKRn4ZjDI",
    publishedAt: "2025-11-28T19:14:51Z",
    likeCount: 142,
    commentCount: 3,
  },
];

const PESQUISA_VIDEOS: Video[] = [
  {
    video_id: "fh9LgKXBGnQ",
    title: "Enterprise Deep Research: The Next Killer App for Enterprise AI — Ofer Mendelevitch, Vectara",
    channel: "AI Engineer",
    duration: "5.316666666666666",
    views: "380",
    viewCount: 380,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=fh9LgKXBGnQ",
    publishedAt: "2025-11-24T20:16:36Z",
    likeCount: 7,
    commentCount: 1,
  },
  {
    video_id: "D5QeUQ4VbjM",
    title: "Anthropic&#39;s New Paper Is WILD",
    channel: "AI LABS",
    duration: "7.1",
    views: "4.4K",
    viewCount: 4376,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=D5QeUQ4VbjM",
    publishedAt: "2025-11-27T13:44:55Z",
    likeCount: 148,
    commentCount: 17,
  },
  {
    video_id: "R6bFj4eq_fs",
    title: "New NotebookLM Upgrade Is Insane! Full Deep Research to Visuals Workflow.",
    channel: "AI and Tech for Education",
    duration: "6.25",
    views: "5.8K",
    viewCount: 5846,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=R6bFj4eq_fs",
    publishedAt: "2025-11-25T12:45:06Z",
    likeCount: 169,
    commentCount: 4,
  },
  {
    video_id: "qYnP7fZJlo8",
    title: "Pesquisa Avançada com NotebookLM: O Segredo que Poucos Conhecem",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=qYnP7fZJlo8",
    publishedAt: "2025-11-26T09:00:54Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "gWqv3NAFfYo",
    title: "Essa IA Faz Tarefas Sozinha pra Você",
    channel: "NoCode StartUp",
    duration: "0.6",
    views: "1.2K",
    viewCount: 1169,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=gWqv3NAFfYo",
    publishedAt: "2025-11-28T14:01:24Z",
    likeCount: 26,
    commentCount: 1,
  },
  {
    video_id: "Lnwv9HdvD94",
    title: "SEU WI-FI PODE EXTERMINAR ABELHAS!",
    channel: "TecMundo",
    duration: "1.0",
    views: "1.5K",
    viewCount: 1489,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Lnwv9HdvD94",
    publishedAt: "2025-11-29T14:00:39Z",
    likeCount: 204,
    commentCount: 12,
  },
];

const NOTICIAS_VIDEOS: Video[] = [
  {
    video_id: "CDHtme89MQo",
    title: "ESTAMOS AO VIVO | Black Friday Canaltech 2025!",
    channel: "Canaltech",
    duration: "323.0",
    views: "23.2K",
    viewCount: 23165,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=CDHtme89MQo",
    publishedAt: "2025-11-28T18:44:08Z",
    likeCount: 888,
    commentCount: 3,
  },
  {
    video_id: "vyeKkvFBSwI",
    title: "BLACK FRIDAY CANALTECH 2025 CHEGOU!",
    channel: "Canaltech",
    duration: "489.0",
    views: "55.1K",
    viewCount: 55146,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=vyeKkvFBSwI",
    publishedAt: "2025-11-28T05:27:18Z",
    likeCount: 2088,
    commentCount: 6,
  },
  {
    video_id: "rce68ElxkxU",
    title: "Samsung Galaxy Z Trifold será MAIS CARO que iPhone dobrável; Rússia usando pombos para espionagem?",
    channel: "TecMundo",
    duration: "10.6",
    views: "4.6K",
    viewCount: 4576,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=rce68ElxkxU",
    publishedAt: "2025-11-28T22:01:00Z",
    likeCount: 834,
    commentCount: 19,
  },
  {
    video_id: "NsirDFaTJ5s",
    title: "TecFriday: 150 anos de jornalismo por R$1,90/mês?",
    channel: "TecMundo",
    duration: "1.2",
    views: "5.1K",
    viewCount: 5070,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=NsirDFaTJ5s",
    publishedAt: "2025-11-28T13:00:54Z",
    likeCount: 20,
    commentCount: 1,
  },
  {
    video_id: "g-mNY8EjvRY",
    title: "Flux 2.0, the FREE alternative to Nano Banana Pro!",
    channel: "Universe of AI",
    duration: "9.8",
    views: "277",
    viewCount: 277,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=g-mNY8EjvRY",
    publishedAt: "2025-11-28T23:29:53Z",
    likeCount: 10,
    commentCount: 0,
  },
  {
    video_id: "0d727qv_MYs",
    title: "You have TWO YEARS LEFT to prepare  - Dr. Roman Yampolskiy",
    channel: "Wes Roth",
    duration: "81.2",
    views: "36.0K",
    viewCount: 36014,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=0d727qv_MYs",
    publishedAt: "2025-11-28T02:05:45Z",
    likeCount: 1086,
    commentCount: 609,
  },
];

const AUTOMACAO_VIDEOS: Video[] = [
  {
    video_id: "Y0Aqc174FMM",
    title: "The most absurd product I&#39;ve made",
    channel: "3Blue1Brown",
    duration: "1.4166666666666667",
    views: "95.7K",
    viewCount: 95723,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Y0Aqc174FMM",
    publishedAt: "2025-11-24T16:30:21Z",
    likeCount: 2325,
    commentCount: 61,
  },
  {
    video_id: "DBgAH8YLvPU",
    title: "Let’s build an automation!",
    channel: "Code with Ania Kubów",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=DBgAH8YLvPU",
    publishedAt: "2025-11-27T14:49:31Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "6xXLss88_14",
    title: "Automate Your Work in Seconds: Pokee AI Workflow Tutorial (2025)",
    channel: "Eric Tech",
    duration: "6.0",
    views: "249",
    viewCount: 249,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=6xXLss88_14",
    publishedAt: "2025-11-28T13:30:15Z",
    likeCount: 10,
    commentCount: 0,
  },
  {
    video_id: "UgEuMuvy8A8",
    title: "How ADE Supercharges Your RAG Pipeline 🚀📄 #ADE #RAG #DocumentAI",
    channel: "LandingAI",
    duration: "0.9",
    views: "8",
    viewCount: 8,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=UgEuMuvy8A8",
    publishedAt: "2025-11-29T14:30:19Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "KZwP-N0ty8E",
    title: "Stop Using Photoshop & Canva.. This AI Thumbnail Maker Replaced Them!",
    channel: "Rob The AI Guy",
    duration: "12.7",
    views: "753",
    viewCount: 753,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=KZwP-N0ty8E",
    publishedAt: "2025-11-28T18:50:32Z",
    likeCount: 44,
    commentCount: 6,
  },
];

const HARDWARE_VIDEOS: Video[] = [
  {
    video_id: "M1edEhABidg",
    title: "GitHub Trending Weekly #12: AlohaMini, ZAPI, cgpu, Z-Image, F1 Race Replay, s&amp;box, corner-shape",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=M1edEhABidg",
    publishedAt: "2025-11-27T12:31:41Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "a7lmyfewf1o",
    title: "Cloudflare Proxy Manager: a CLI tool for anyone managing domains on Cloudflare. #github",
    channel: "Github Awesome",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=a7lmyfewf1o",
    publishedAt: "2025-11-21T03:10:53Z",
    likeCount: 0,
    commentCount: 0,
  },
  {
    video_id: "Fh-DUfdt5YY",
    title: "From Cloud to VPC: Deploy ADE Anywhere 🚀☁️ #ade #vpc #deployment",
    channel: "LandingAI",
    duration: "0.9",
    views: "124",
    viewCount: 124,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=Fh-DUfdt5YY",
    publishedAt: "2025-11-28T14:30:23Z",
    likeCount: 2,
    commentCount: 0,
  },
  {
    video_id: "SKMXsdCWpzY",
    title: "Building the Modern Quantum Architecture: Lecture 2 — Utility Scale Quantum Architecture",
    channel: "Microsoft Azure",
    duration: "15.1",
    views: "84",
    viewCount: 84,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=SKMXsdCWpzY",
    publishedAt: "2025-11-29T16:00:53Z",
    likeCount: 14,
    commentCount: 0,
  },
  {
    video_id: "mj5m2PA8eoc",
    title: "GOVERNO DERRUBA 300 SITES DE FILMES E SÉRIES! TESLA vira Fábrica de Chips e VAZAMENTO na OpenAI!",
    channel: "TecMundo",
    duration: "10.7",
    views: "11.1K",
    viewCount: 11082,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=mj5m2PA8eoc",
    publishedAt: "2025-11-27T22:00:56Z",
    likeCount: 1374,
    commentCount: 81,
  },
];

const PRODUTIVIDADE_VIDEOS: Video[] = [
  {
    video_id: "TylLn2qfWVw",
    title: "Dicas para o Uso Profissional de IA!",
    channel: "Inteligencia Artificial para advogados",
    duration: "0",
    views: "0",
    viewCount: 0,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=TylLn2qfWVw",
    publishedAt: "2025-11-22T16:01:00Z",
    likeCount: 0,
    commentCount: 0,
  },
];

const NEGOCIOS_VIDEOS: Video[] = [
  {
    video_id: "w5E24ZvkzNM",
    title: "Para avançar no ESG, empresas apostam na formação de jovens aprendizes",
    channel: "exame",
    duration: "22.7",
    views: "173",
    viewCount: 173,
    summary: "",
    keyPoints: [],
    url: "https://www.youtube.com/watch?v=w5E24ZvkzNM",
    publishedAt: "2025-11-28T20:33:09Z",
    likeCount: 6,
    commentCount: 0,
  },
];

// Categorias com metadados

const OUTROS_CATEGORY: Category = {
  id: "outros",
  name: "Outros",
  emoji: "📌",
  description: "Outros tópicos relevantes",
  videoCount: 39,
  videos: OUTROS_VIDEOS,
};

const FERRAMENTAS_DEV_CATEGORY: Category = {
  id: "ferramentas-dev",
  name: "Ferramentas para Devs",
  emoji: "💻",
  description: "IDEs, copilots e ferramentas de desenvolvimento",
  videoCount: 34,
  videos: FERRAMENTAS_DEV_VIDEOS,
};

const NOVOS_MODELOS_CATEGORY: Category = {
  id: "novos-modelos",
  name: "Novos Modelos",
  emoji: "🚀",
  description: "Lançamentos e atualizações de modelos de IA",
  videoCount: 25,
  videos: NOVOS_MODELOS_VIDEOS,
};

const TUTORIAIS_CATEGORY: Category = {
  id: "tutoriais",
  name: "Tutoriais",
  emoji: "📚",
  description: "Guias e tutoriais práticos",
  videoCount: 20,
  videos: TUTORIAIS_VIDEOS,
};

const AGENTES_IA_CATEGORY: Category = {
  id: "agentes-ia",
  name: "Agentes de IA",
  emoji: "🤖",
  description: "Agentes autônomos e sistemas multi-agente",
  videoCount: 16,
  videos: AGENTES_IA_VIDEOS,
};

const PESQUISA_CATEGORY: Category = {
  id: "pesquisa",
  name: "Pesquisa",
  emoji: "🔬",
  description: "Papers e pesquisas acadêmicas",
  videoCount: 6,
  videos: PESQUISA_VIDEOS,
};

const NOTICIAS_CATEGORY: Category = {
  id: "noticias",
  name: "Notícias",
  emoji: "📰",
  description: "Notícias e atualizações do mundo da IA",
  videoCount: 6,
  videos: NOTICIAS_VIDEOS,
};

const AUTOMACAO_CATEGORY: Category = {
  id: "automacao",
  name: "Automação",
  emoji: "⚙️",
  description: "Workflows e automação com IA",
  videoCount: 5,
  videos: AUTOMACAO_VIDEOS,
};

const HARDWARE_CATEGORY: Category = {
  id: "hardware",
  name: "Hardware & Infra",
  emoji: "🖥️",
  description: "GPUs, chips e infraestrutura",
  videoCount: 5,
  videos: HARDWARE_VIDEOS,
};

const PRODUTIVIDADE_CATEGORY: Category = {
  id: "produtividade",
  name: "Produtividade",
  emoji: "📈",
  description: "Dicas e ferramentas de produtividade",
  videoCount: 1,
  videos: PRODUTIVIDADE_VIDEOS,
};

const NEGOCIOS_CATEGORY: Category = {
  id: "negocios",
  name: "Negócios & Startups",
  emoji: "💼",
  description: "IA para negócios e empreendedorismo",
  videoCount: 1,
  videos: NEGOCIOS_VIDEOS,
};

// Edição completa
export const REAL_EDITION: Edition = {
  id: "2025-11-29",
  weekLabel: "Semana de 29/11/2025",
  dateRange: "27–29 nov 2025",
  tagline: "Sua curadoria semanal de IA",
  collectedAt: "2025-11-29T14:10:25.044114",
  totalVideos: 158,
  categories: [
    OUTROS_CATEGORY,
    FERRAMENTAS_DEV_CATEGORY,
    NOVOS_MODELOS_CATEGORY,
    TUTORIAIS_CATEGORY,
    AGENTES_IA_CATEGORY,
    PESQUISA_CATEGORY,
    NOTICIAS_CATEGORY,
    AUTOMACAO_CATEGORY,
    HARDWARE_CATEGORY,
    PRODUTIVIDADE_CATEGORY,
    NEGOCIOS_CATEGORY,
  ],
  summaryHighlights: [
    { categoryName: "Outros", emoji: "📌", videoCount: 39 },
    { categoryName: "Ferramentas para Devs", emoji: "💻", videoCount: 34 },
    { categoryName: "Novos Modelos", emoji: "🚀", videoCount: 25 },
    { categoryName: "Tutoriais", emoji: "📚", videoCount: 20 },
    { categoryName: "Agentes de IA", emoji: "🤖", videoCount: 16 },
  ],
};

// Helper para obter todos os vídeos
export function getAllRealVideos(): Video[] {
  return REAL_EDITION.categories.flatMap(c => c.videos);
}

// Helper para obter itens aleatórios para o ticker de notícias
export function getRandomRealNewsItems(count: number): Video[] {
  const allVideos = getAllRealVideos();
  const shuffled = [...allVideos].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
